### ISSUE TITLE
Use BASE64 encoded image data?

### ISSUE THREAD

**Issue by DivineOmega** [iMicknl/cordova-plugin-openalpr#18]
Is it possible to pass in BASE64 encoded image data into the `scan` method rather than a file path to the image?

**Comment by melvinversluijs** [comment]
Hi @DivineOmega,

It is currently not possible to pass a Base64 encoded string to the scan method. This is however an enhancement we would like to add in the future. For now you could check out issue#15 (https://github.com/iMicknl/cordova-plugin-openalpr/issues/15) which has an explanation on how to use a Base64 encoded string instead of an image path with this plugin  (This currently only works for Android which is why we have not released it yet).  

If you have any questions feel free to ask.

Kind regards,
Melvin

**Comment by iMicknl** [comment]
We just released the 2.0.0 version of the plugin, which supports Base64 encode image data on iOS and Android.
